version: '3'

services:
  mongo:
    image: 'bitnami/mongodb'
    restart: 'always'
    environment:
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_DATABASE: ${MONGO_DB}
    ports:
      - 27017:27017

  postgres:
    image: 'bitnami/postgresql'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  redis:
    image: redis:6
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  replicator:
    build: .
    image: ghcr.io/osoc21/ldes-replicator
    environment:
      URLS: https://apidg.gent.be/opendata/adlib2eventstream/v1/dmg/objecten
      STATE_CONFIG: '{"id":"replicator_0",
        "host":"redis",
        "port":6379}'
      POLL_INTERVAL: '5000'
      CONNECTORS: '[0,1]'
      CONNECTOR_0_TYPE: '@ldes/ldes-postgres-connector'
      CONNECTOR_0_CONFIG: '{"amountOfVersions":0,
        "tableName":"ldes",
        "username":"${POSTGRES_USER}",
        "password":"${POSTGRES_PASSWORD}",
        "database":"${POSTGRES_DB}",
        "hostname":"postgres",
        "port":5432}'
      CONNECTOR_1_TYPE: '@ldes/ldes-mongodb-connector'
      CONNECTOR_1_CONFIG: '{"amountOfVersions":0,
        "username":"${MONGO_USER}",
        "password":"${MONGO_PASSWORD}",
        "database":"${MONGO_DB}",
        "hostname":"mongo",
        "port":27017}'
