repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql
    chart: bitnami/postgresql
    namespace: ldes
    createNamespace: true
    values:
      - postgresqlUsername: user2
      - postgresqlPassword: password2
      - postgresqlDatabase: db2

  - name: redis
    chart: bitnami/redis
    namespace: ldes
    createNamespace: true
    values:
      - master.service.nodePort: "6379"
      - auth.enabled: false
      - replica.replicaCount: 0

  - name: ldes-replicator
    chart: ./ldes-replicator-helm
    namespace: ldes
    createNamespace: true
    values:
      - replicator:
          urls:
            - "https://smartdata.dev-vlaanderen.be/base/straatnaam"
          state:
            id: 'replicator'
            host: 'redis-master'
          polling_interval: 5000
        connectors:
          PG:
            type: '@ldes/ldes-postgres-connector'
            settings:
              amountOfVersions: 0
              tableName: ldes
              username: user2
              password: password2
              database: db2
              hostname: postgresql
              port: 5432
